### ISSUE TITLE
command api error

### ISSUE THREAD

**Issue by blue-pinapple** [R2bEEaton-Minecraft/CoreProtectTimeLapse#12]
```
[16:54:22 INFO]: Starting minecraft server version 1.21.1
[16:54:22 INFO]: Loading properties
[16:54:22 INFO]: This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[16:54:23 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[16:54:23 INFO]: Server Ping Player Sample Count: 12
[16:54:23 INFO]: Using 4 threads for Netty based IO
[16:54:23 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and population gen parallelism of 2 threads
[16:54:23 INFO]: Default game type: SURVIVAL
[16:54:23 INFO]: Generating keypair
[16:54:23 INFO]: Starting Minecraft server on *:25565
[16:54:23 INFO]: Using default channel type
[16:54:24 INFO]: Paper: Using libdeflate (macOS ARM64 / Apple Silicon) compression from Velocity.
[16:54:24 INFO]: Paper: Using native (macOS ARM64 / Apple Silicon) cipher from Velocity.
[16:54:24 INFO]: [CoreProtect] Loading server plugin CoreProtect v22.4
[16:54:24 INFO]: [CoreProtectTimeLapse] Loading server plugin CoreProtectTimeLapse vv1.0.4
[16:54:24 ERROR]: [CoreProtectTimeLapse] Error initializing plugin 'CoreProtectTimeLapse-v1.0.4-all.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
cc.spea.CoreProtectTimeLapse.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.21.1
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:73) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.commandapi.CommandAPI.onLoad(CommandAPI.java:103) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.Main.onLoad(Main.java:16) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:547) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[16:54:24 INFO]: [CommandAPI] Loading server plugin CommandAPI v9.6.1
[16:54:24 INFO]: [CommandAPI] Loaded platform NMS_1_21_R1 > NMS_Common > CommandAPIBukkit
[16:54:24 INFO]: [CommandAPI] Hooked into Spigot successfully for Chat/ChatComponents
[16:54:24 INFO]: [CommandAPI] Hooked into Adventure for AdventureChat/AdventureChatComponents
[16:54:24 INFO]: [CommandAPI] Hooked into Paper for paper-specific API implementations
[16:54:24 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:54:24 INFO]: Preparing level "world"
[16:54:24 INFO]: Preparing start region for dimension minecraft:overworld
[16:54:25 INFO]: Time elapsed: 590 ms
[16:54:25 INFO]: Preparing start region for dimension minecraft:the_nether
[16:54:25 INFO]: Time elapsed: 64 ms
[16:54:25 INFO]: Preparing start region for dimension minecraft:the_end
[16:54:25 INFO]: Time elapsed: 39 ms
[16:54:25 INFO]: [CoreProtect] Enabling CoreProtect v22.4
[16:54:25 INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
[16:54:25 INFO]: [CoreProtect] Using SQLite for data storage.
[16:54:25 INFO]: --------------------
[16:54:25 INFO]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[16:54:25 INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[16:54:25 INFO]: --------------------
[16:54:25 INFO]: [CoreProtectTimeLapse] Enabling CoreProtectTimeLapse vv1.0.4
[16:54:25 ERROR]: Error occurred while enabling CoreProtectTimeLapse vv1.0.4 (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:169) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.commandapi.CommandAPI.onEnable(CommandAPI.java:135) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.Main.onEnable(Main.java:25) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
	[16:54:25 INFO]: [CoreProtectTimeLapse] Disabling CoreProtectTimeLapse vv1.0.4
[16:54:25 INFO]: [CommandAPI] Enabling CommandAPI v9.6.1
[16:54:25 INFO]: [CommandAPI] Hooked into Paper ServerResourcesReloadedEvent
[16:54:25 INFO]: [spark] Starting background profiler...
[16:54:26 INFO]: Done preparing level "world" (2.124s)

	```
	I seem to be getting this error
	it loads before CommandAPI starts
	paper: 1.21.1
	CommandAPI: 9.6.1 Mojang maped
	CoreProtect Time-Lapse: v1.0.4
	Coreprotect: 22.4

**Comment by blue-pinapple** [comment]
This is the error I get without command api
```
[21:08:10 ERROR]: [CoreProtectTimeLapse] Error initializing plugin 'CoreProtectTimeLapse-v1.0.4-all.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
cc.spea.CoreProtectTimeLapse.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.21
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:73) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.commandapi.CommandAPI.onLoad(CommandAPI.java:103) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at CoreProtectTimeLapse-v1.0.4-all.jar/cc.spea.CoreProtectTimeLapse.Main.onLoad(Main.java:16) ~[CoreProtectTimeLapse-v1.0.4-all.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-103-aa3b356]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-103-aa3b356]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-103-aa3b356]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-103-aa3b356]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-103-aa3b356]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-103-aa3b356]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-103-aa3b356]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-103-aa3b356]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
	```

**Comment by blue-pinapple** [comment]
For now, I just went back to 1.20.4 on the old version
I need to know one last thing
I am using a backup world, but because I am using MySQL I am using the live server data
Does it write to the database or only read?
So if it crashes is my data safe?

**Comment by R2bEEaton** [comment]
Hi! Sorry I missed this! I never updated the plugin to 1.21 or higher because as far as I'm aware, the free version of CoreProtect itself hasn't updated. As such, the dependency on Command API are not fixed either. Working with 1.20.4 for now would be your best bet as you discovered.

The plugin does write to the database because it is performing rollbacks and restores to change the world. I suppose in theory if you always restore any change you make when using CPTL the database might be fine, but definitely don't run the servers at the same time. AND if you have the means you should 200% use a copy of the database because I can't guarantee anything I just said being true.

Since its been a while since your issue and you may have tried these things, please update us on your experience!

**Comment by heypr** [comment]
Heya! Funnily enough, I PR'd right in between the release of 1.21 and 1.21.1. The version just needs to be bumped & tested.

**Comment by heypr** [comment]
Also quick safety thing, perhaps have some sort of check to see if any non-operators/users without some plugin-specific permission are on, and kick them accordingly? Additionally, maybe send a message in chat suggesting that admins running the command make a copy of the database/server? A double confirmation might help with that too, perhaps something along the lines of "Are you sure you've taken a backup of your server and/or database?"

**Comment by R2bEEaton** [comment]
@heypr Hey there! Thanks for the info. I'm swamped right now so I've added it to my long to-do list! And great suggestions on the double confirmation.

Unrelated to this question - I assume you've used the plugin, and I'd love to see some videos if you have the time!

**Comment by heypr** [comment]
> @heypr Hey there! Thanks for the info. I'm swamped right now so I've added it to my long to-do list! And great suggestions on the double confirmation.
> 
> Unrelated to this question - I assume you've used the plugin, and I'd love to see some videos if you have the time!

Sorry, missed your comment! 

I haven't taken any videos just yet, as I'm waiting for some more progress to be done on the SMP. I'll definitely update you if and when I create the timelapse though! It'll likely be done after every academic year, so I'm aiming to have create it around May or so.
